### PR TITLE
Add max values for the bands, for easier normalization

### PR DESCRIPTION
**Pull request by gabrieltseng**
Re-iterating through new datasets to calculate the normalizing dict can be onerous. 

This code adds a new constant to `cropharvest.engineer` which exposes the expected maximum values for each band; this can be substituted for normalization of the bands.

### CODE REVIEW

**Comment by gabrieltseng** [comment]
@ivanzvonkov yes I think thats better. Consolidated!

The failing tests seem unrelated (it fails during setup) so I'll try and figure out what's happening but in the meantime the code should be good to re-review.

**Comment by gabrieltseng** [comment]
@ivanzvonkov , it seems like the build is just broken for Windows. Would it be worth skipping windows for now and adding an issue, to get this through?

**Review by ivanzvonkov — APPROVED** [review]
LGTM

**Comment by gabrieltseng** [comment]
This got merged into `main` but somehow its not reflected in this PR. Closing

**Pull request closed without merging**
